### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by kirtiwardhan-18** [Raw-Developers/Iris-Flower#1]
Code has some spelling mistakes and syntax issues. PS also check for white spaces

**Comment by aishwarya-g-thoughtworks** [comment]
This issue had already been fixed by the previous merge you had made, so you can close this issue.

**Comment by alteregoprofile** [comment]
Hello, Please check my modifications!

**Comment by kirtiwardhan-18** [comment]
Kindly accept the invitation so that we can assign you the issue.
